### ISSUE TITLE
We should cache the stats 

### ISSUE THREAD

**Issue by hampelm** [LocalData/localdata-api#127]
We should use a combination of time + count to cache the stats. This would improve performance, especially for the tileserver. 

Unfortunately we can't incrementally update the stats in all situations, since old responses might be deleted.

Should we add a model for this? Should we use an external service for caching? I'd vote for adding a cache model with properties for `count`, `survey`, `timestamp`, `key`, and `value`.

**Comment by prashtx** [comment]
We now cache stats through a generic cache component, which currently uses a MongoDB strategy but could be switched to a redis or other strategy.
