### ISSUE TITLE
KML/CSV export breaks for large response sets

### ISSUE THREAD

**Issue by prashtx** [LocalData/localdata-api#42]
If we ask Mongoose for very large result sets, we encounter a parseError. For the `.../responses` and `.../responses.geojson` endpoints, we require the client to specify a range. For CSV and KML export, we might need to request the data from the database in chunks.

Ideally, we can stream the data in and out, so that we don't risk creating extremely large data structures in memory.

**Comment by hampelm** [comment]
This was fixed by the new export system.
